# Create PersistentVolume
# change the ip of NFS server
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-pv
  labels:
    app: elk
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /k8s/elk/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elk-pvc
  labels:
    app: elk
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
