apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: elasticsearch-data
  namespace: elk
  labels:
    app: elasticsearch-data
    env: prod
spec:
  selector:
    matchLabels:
      app: elasticsearch-data
  template:
    metadata:
      labels:
        app: elasticsearch-data
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch-data
        image: behroozam/elasticsearch:6.5.1
        imagePullPolicy: Always
        env:
        - name: discovery.zen.ping.unicast.hosts
          value: elasticsearch-data,elasticsearch-master
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: cluster.name
          value: yourcluster
        - name: node.data
          value: "true"
        - name: node.master
          value: "false"
        - name: node.ingest
          value: "false"
        - name: bootstrap.memory_lock
          value:  "false"
        - name: ES_JAVA_OPTS
          value: -Xms16g -Xmx16g
        resources:
          limits:
            cpu: 12
            memory: "32Gi"
        ports:
        - containerPort: 9300
          name: transport
        volumeMounts:
        - name: elasticsearch-data-storage
          mountPath: /data
        - name: tz-config
          mountPath: /etc/localtime
      volumes:
      - name: elasticsearch-data-storage
        persistentVolumeClaim:
          claimName: elk-pvc
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Asia/Tehran
      nodeSelector:
        elk: "data"

