---
apiVersion: v1
kind: Service
metadata:
  namespace: elk 
  name: elasticsearch
  labels:
    env: prod
spec:
  type: ClusterIP
  selector:
    app: elasticsearch-client
  ports:
  - name: http
    port: 9200
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  namespace: elk 
  name: elasticsearch-data
  labels:
    env: prod
spec:
  clusterIP: None
  selector:
    app: elasticsearch-data
  ports:
  - port: 9300
    name: transport
---
apiVersion: v1
kind: Service
metadata:
  namespace: elk 
  name: elasticsearch-discovery
  labels:
    env: prod
spec:
  selector:
    app: elasticsearch-master
  ports:
  - name: transport
    port: 9300
    protocol: TCP